### ISSUE TITLE
ToDo App 요구사항 명세서 작성

### ISSUE THREAD

**Issue by jylee-me** [jylee-me/Todo-App#1]
### 만들고자 하는 기능이 무엇인가요?
- Todo 생성 기능

### 해당 기능을 구현하기 위해 할 일이 무엇인가요?
1. [ ] 기능 요구사항 작성하기
2. [ ] API 명세서 작성하기
3. [ ] 테이블 구성 명세서 작성하기

### 예상 작업 시간
3시간
